// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Contexto;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(AplicacaoDbContext))]
    [Migration("20251213195625_migration_13_12_25__02")]
    partial class migration_13_12_25__02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeFederacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFederacaoId");

                    b.ToTable("Cidade", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Endereco", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.UnidadeFederacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadeFederacao", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caracteristica", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Quartos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("VagasGaragem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Imovel", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.ImovelCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("ImovelId", "CaracteristicaId")
                        .IsUnique();

                    b.ToTable("ImovelCaracteristica", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.Imovel.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tipo", "Imovel");
                });

            modelBuilder.Entity("Dominio.Entidades.Testes.T_Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Versao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("T_Orcamento");
                });

            modelBuilder.Entity("Dominio.Entidades.Testes.T_Orcamento_Servicos", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("preco_hora_pintura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidade_horas_pintura")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("T_Orcamento_Servicos");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Cidade", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.UnidadeFederacao", "UnidadeFederacao")
                        .WithMany()
                        .HasForeignKey("UnidadeFederacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFederacao");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Endereco", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.ImovelCaracteristica", b =>
                {
                    b.HasOne("Dominio.Entidades.Imobiliaria.Caracteristica", "Caracteristica")
                        .WithMany("ImoveisCaracteristicas")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Imobiliaria.Imovel", "Imovel")
                        .WithMany("ImoveisCaracteristicas")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Dominio.Entidades.Testes.T_Orcamento_Servicos", b =>
                {
                    b.HasOne("Dominio.Entidades.Testes.T_Orcamento", "Orcamento")
                        .WithOne("Servicos")
                        .HasForeignKey("Dominio.Entidades.Testes.T_Orcamento_Servicos", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Caracteristica", b =>
                {
                    b.Navigation("ImoveisCaracteristicas");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.Navigation("ImoveisCaracteristicas");
                });

            modelBuilder.Entity("Dominio.Entidades.Testes.T_Orcamento", b =>
                {
                    b.Navigation("Servicos")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
