// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Contexto;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(AplicacaoDbContext))]
    [Migration("20251127230941_migration_004")]
    partial class migration_004
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeFederacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeFederacaoId");

                    b.ToTable("Cidade", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Endereco", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.UnidadeFederacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadeFederacao", "Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caracteristica", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<byte>("Quartos")
                        .HasColumnType("tinyint");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("int");

                    b.Property<byte>("VagasGaragem")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Imovel", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.ImovelCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("int");

                    b.Property<int>("ImovelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("ImovelId", "CaracteristicaId")
                        .IsUnique();

                    b.ToTable("ImovelCaracteristica", "Imobiliaria");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Cidade", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.UnidadeFederacao", "UnidadeFederacao")
                        .WithMany()
                        .HasForeignKey("UnidadeFederacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeFederacao");
                });

            modelBuilder.Entity("Dominio.Entidades.EnderecoNS.Endereco", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.HasOne("Dominio.Entidades.EnderecoNS.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.ImovelCaracteristica", b =>
                {
                    b.HasOne("Dominio.Entidades.Imobiliaria.Caracteristica", "Caracteristica")
                        .WithMany("ImoveisCaracteristicasBB")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Imobiliaria.Imovel", "Imovel")
                        .WithMany("ImoveisCaracteristicas")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Caracteristica", b =>
                {
                    b.Navigation("ImoveisCaracteristicasBB");
                });

            modelBuilder.Entity("Dominio.Entidades.Imobiliaria.Imovel", b =>
                {
                    b.Navigation("ImoveisCaracteristicas");
                });
#pragma warning restore 612, 618
        }
    }
}
